### ISSUE TITLE
Learn Javascript

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/CartoCosmos#1]
Most of the development for this project will be in Javascript, learning the basics will be useful as you start working with existing libraries:

https://www.w3schools.com/js/

**Comment by irishes** [comment]
Another great resource for learning about JS. https://developer.mozilla.org/en-US/docs/Web/JavaScript

**Comment by mahunterUSGS** [comment]
Not JS related, but it was mentioned that a basic map projection reference would be useful. Here's a great USGS poster to put on your wall:
https://store.usgs.gov/assets/mod/storefiles/PDF/16573.pdf

**Comment by kaitlyndlee** [comment]
Can we close this?
