### ISSUE TITLE
Provide the previous Astro version of OpenLayers

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/CartoCosmos#12]
Let's put a copy of the most recent Astro custom OpenLayers library in:

- [ ] /work/projects/webteam/openlayers

**Comment by irishes** [comment]
Should I copy the git version of astrowebmaps4 to the work/projects/webteam/openlayes directory?

**Comment by thareUSGS** [comment]
Now that is push to github, I think we can remove the "openlayers" directory (or even add a note for the github site).

**Comment by kaitlyndlee** [comment]
Can we close this issue?
