### ISSUE TITLE
Create Layer Switcher

### ISSUE THREAD

**Issue by kaitlyndlee** [USGS-Astrogeology/CartoCosmos#15]
OL 6 does not have a layer switcher and the old switcher in AstroWebMaps wraps an old implementation of the OL layer switcher. We need to take the functionality of the layer switcher in AstroWebMaps and abstract OL from it.

**Comment by thareUSGS** [comment]
this fact (also here https://github.com/openlayers/openlayers/issues/10082 ) might be a show-stopper for OL6. Looks like OL5 still has the same layer code.

**Comment by jlaura** [comment]
Does something like this help? 

https://github.com/walkermatt/ol-layerswitcher

Looks like a very popular project and a very brief skim of the repo makes it sounds like it is designed for OL >= 5.

**Comment by jlaura** [comment]
Crud...I looked again. Looks like version 3-5. Apologies for the noise.

**Comment by USGSsakins** [comment]
It may be too early to use OL6 the layer switcher may be something they add later.  It looks like they are recommend 5.3 if you're not ready for 6

https://github.com/openlayers/openlayers/releases/tag/v5.3.0
